// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxekcssuzixhieadgcxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZWtjc3N1eml4aGllYWRnY3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODAyNDAsImV4cCI6MjA2NDI1NjI0MH0.FLfZG0BEaT9f0E6JTMtRaYUgrgCmbvzfIt5oBp1AprU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});